### ISSUE TITLE
pip install -r requirements.txt fails

### ISSUE THREAD

**Issue by yuvipanda** [wiki-ai/ores#46]
```python
Ignoring link https://pypi.python.org/packages/source/s/scipy/scipy-0.9.0.zip#md5=a37933c9e3c4fdf8d087624cd7dcb47d (from https://pypi.python.
org/simple/scipy/), version 0.9.0 doesn't match ==0.15.1
  Using version 0.15.1 (newest of versions: 0.15.1, 0.15.1)
  Downloading from URL https://pypi.python.org/packages/source/s/scipy/scipy-0.15.1.tar.gz#md5=be56cd8e60591d6332aac792a5880110 (from https://p
ypi.python.org/simple/scipy/)
  Running setup.py (path:/home/yuvipanda/build/scipy/setup.py) egg_info for package scipy
    Download error on https://pypi.python.org/simple/numpy/: [X509] PEM lib (_ssl.c:2734) -- Some packages may not be found!
    Couldn't find index page for 'numpy' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [X509] PEM lib (_ssl.c:2734) -- Some packages may not be found!
    No local packages or download links found for numpy>=1.5.1
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/yuvipanda/build/scipy/setup.py", line 249, in <module>
        setup_package()
      File "/home/yuvipanda/build/scipy/setup.py", line 246, in setup_package
        setup(**metadata)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/yuvipanda/lib/python3.4/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/yuvipanda/lib/python3.4/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/home/yuvipanda/lib/python3.4/site-packages/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/yuvipanda/lib/python3.4/site-packages/pkg_resources.py", line 818, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/yuvipanda/lib/python3.4/site-packages/pkg_resources.py", line 830, in obtain
        return installer(requirement)
      File "/home/yuvipanda/lib/python3.4/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/yuvipanda/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 587, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('numpy>=1.5.1')
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/numpy/: [X509] PEM lib (_ssl.c:2734) -- Some packages may not be found!
```

**Comment by he7d3r** [comment]
I was unable to reproduce this on Ubuntu 14.10 with my local branch at de5d945.
