### ISSUE TITLE
Celery logs full of exceptions. 

### ISSUE THREAD

**Issue by halfak** [wiki-ai/ores#84]
For example:

```
Sep 10 11:21:15 ores-worker-01 celery[17746]: Traceback (most recent call last):
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
Sep 10 11:21:15 ores-worker-01 celery[17746]: R = retval = fun(*args, **kwargs)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
Sep 10 11:21:15 ores-worker-01 celery[17746]: return self.run(*args, **kwargs)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/celery.py", line 38, in _score_task
Sep 10 11:21:15 ores-worker-01 celery[17746]: return Timeout._score(self, context, model, rev_id, cache=cache)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/score_processor.py", line 44, in _score
Sep 10 11:21:15 ores-worker-01 celery[17746]: return self._process(context, model, process_cache)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/timeout.py", line 21, in _process
Sep 10 11:21:15 ores-worker-01 celery[17746]: seconds=self.timeout)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/timeout.py", line 62, in timeout
Sep 10 11:21:15 ores-worker-01 celery[17746]: result = func(*args, **kwargs)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/score_processor.py", line 31, in _process
Sep 10 11:21:15 ores-worker-01 celery[17746]: score = scoring_context.score(model, cache)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/scoring_contexts/scoring_context.py", line 45, in score
Sep 10 11:21:15 ores-worker-01 celery[17746]: feature_values = list(self.solve(model, cache))
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 251, in _solve_many
Sep 10 11:21:15 ores-worker-01 celery[17746]: value, cache, history = _solve(dependent, context, cache)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 229, in _solve
Sep 10 11:21:15 ores-worker-01 celery[17746]: cache=cache, history=history)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 229, in _solve
Sep 10 11:21:15 ores-worker-01 celery[17746]: cache=cache, history=history)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 229, in _solve
Sep 10 11:21:15 ores-worker-01 celery[17746]: cache=cache, history=history)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 229, in _solve
Sep 10 11:21:15 ores-worker-01 celery[17746]: cache=cache, history=history)
Sep 10 11:21:15 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/dependencies/functions.py", line 241, in _solve
Sep 10 11:21:15 ores-worker-01 celery[17746]: raise CaughtDependencyError(message, e, tb)
Sep 10 11:21:15 ores-worker-01 celery[17746]: revscoring.errors.CaughtDependencyError: TimeoutException: Failed to process <revscoring.languages.english.parent_revision.badwords>:
```

and 

```
Sep 10 10:41:05 ores-worker-01 celery[17746]: [2015-09-10 10:41:05,212: ERROR/MainProcess] Task ores.score_processors.celery._score_task[frwiki:reverted:118516900:0.3.0] raised unex
pected: AttributeError("'NoneType' object has no attribute 'json'",)
Sep 10 10:41:05 ores-worker-01 celery[17746]: Traceback (most recent call last):
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/celery/app/trace.py", line 240, in trace_task
Sep 10 10:41:05 ores-worker-01 celery[17746]: R = retval = fun(*args, **kwargs)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/celery/app/trace.py", line 438, in __protected_call__
Sep 10 10:41:05 ores-worker-01 celery[17746]: return self.run(*args, **kwargs)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/celery.py", line 38, in _score_task
Sep 10 10:41:05 ores-worker-01 celery[17746]: return Timeout._score(self, context, model, rev_id, cache=cache)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/score_processor.py", line 39, in _score
Sep 10 10:41:05 ores-worker-01 celery[17746]: caches={rev_id: cache})[rev_id]
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/score_processors/score_processor.py", line 23, in _get_root_ds
Sep 10 10:41:05 ores-worker-01 celery[17746]: return scoring_context.extract_roots(model, rev_ids, caches=caches)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/ores/scoring_contexts/scoring_context.py", line 76, in extract_roots
Sep 10 10:41:05 ores-worker-01 celery[17746]: for rev_id, (error, root_vals) in zip(rev_ids, error_root_vals):
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/extractors/api.py", line 140, in _extract_many
Sep 10 10:41:05 ores-worker-01 celery[17746]: rev_docs = self.get_rev_doc_map(rev_ids_missing_data)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/extractors/api.py", line 197, in get_rev_doc_map
Sep 10 10:41:05 ores-worker-01 celery[17746]: properties=props)}
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/revscoring/extractors/api.py", line 194, in <dictcomp>
Sep 10 10:41:05 ores-worker-01 celery[17746]: return {rd['revid']: rd
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/mw/api/collections/revisions.py", line 131, in query
Sep 10 10:41:05 ores-worker-01 celery[17746]: rev_docs, rvcontinue = self._query(*args, **kwargs)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/mw/api/collections/revisions.py", line 188, in _query
Sep 10 10:41:05 ores-worker-01 celery[17746]: doc = self.session.get(params)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/mw/util/api.py", line 30, in get
Sep 10 10:41:05 ores-worker-01 celery[17746]: return self.request('GET', params, **kwargs)
Sep 10 10:41:05 ores-worker-01 celery[17746]: File "/srv/ores/venv/lib/python3.4/site-packages/mw/api/session.py", line 129, in request
Sep 10 10:41:05 ores-worker-01 celery[17746]: doc = super().request(type, params, **kwargs).json()
Sep 10 10:41:05 ores-worker-01 celery[17746]: AttributeError: 'NoneType' object has no attribute 'json'
```

The latter should be handled better.

**Comment by yuvipanda** [comment]
Yup, any 'expected' exception that's passed back to web shouldn't be in the logs.

**Comment by halfak** [comment]
Every exception is passed back to the web, so maybe we should just mark all children of Exception as expected?

**Comment by yuvipanda** [comment]
'every exception' - even ones like, 'redis connection failed'? How do they pass back to the web?

**Comment by halfak** [comment]
Good point.  I've never seen that one.  If an exception occurs while the score is being generated (no redis connection used there) then the exception description is formatted and sent back to the client.  If an exception is raised outside of the context of score() generation, that would be unexpected.

**Comment by yuvipanda** [comment]
Indeed, and those are the ones that are 'interesting' from an ops perspective and should be listed out separately, IMO. A redis connection failure / socket overrun / etc. They can't be sent back to the client in some cases (when redis is dead, as an example).

**Comment by halfak** [comment]
Yeah.  I'm still a little worried of catching *every* error that can happen in the context of scoring.  For now, I'll just try to catch all the common ones.

**Comment by halfak** [comment]
Sorry... tell celery that they are "Expected" -- I always *catch* the errors either way.

**Comment by halfak** [comment]
I've got an open PR to pyenchant to get rid of the "This UTF-8 encoding can't convert to UTF-16:" warning.

See https://github.com/rfk/pyenchant/pull/59

**Comment by halfak** [comment]
The last issue was addressed here: https://github.com/wiki-ai/revscoring/pull/191
